name: CI/CD Pipeline Bati Bloomberg

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: bati-bloomberg
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Build Environment
        run: |
          cp /opt/bloomberg_scheduler/.env.production ./.env
          cp /opt/bloomberg_scheduler/ps-credential.txt ./ps-credential.txt
          docker compose pull

      - name: Build and Start Docker Containers
        run: |
          docker compose up -d --build

  test:
    runs-on: bati-bloomberg
    needs: build
    steps:
      # - name: Run Unit Tests
      #  run: |
      #    docker compose exec airflow-scheduler pytest || exit 1

      - name: Health Check
        run: |
          echo "Checking application health"
          health_check=$(curl -s http://localhost:8080/health)
          echo "Health check response: $health_check"
          if echo "$health_check" | grep -q '"status": "healthy"'; then
            echo "Health check passed"
          else
            echo "Health check failed"
            exit 1
          fi

  deploy:
    runs-on: bati-bloomberg
    needs: [build, test] # Deploy only after successful build and test
    steps:
      - name: Setup Deploy Environment
        run: |
          cp /opt/bloomberg_scheduler/.env.production ./.env
          cp /opt/bloomberg_scheduler/ps-credential.txt ./ps-credential.txt

      - name: Deploy to Server
        run: |
          docker compose restart

      - name: Clean Up Resources
        run: |
          echo "Cleaning up unused Docker resources"
          docker system prune -f --volumes
