name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: bati-bloomberg

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setups environment Build
        run: |
          cp /opt/bloomberg_scheduler/.env.production ./.env

      - name: Build Docker image
        run: |
          docker compose -f docker-compose.yaml up -d --build

  deploy:
    runs-on: bati-bloomberg
    needs: build

    steps:
      - name: Setups environment Deployment
        run: |
          cp /opt/bloomberg_scheduler/.env.production ./.env

      - name: Deploy to server
        run: |
          docker compose -f docker-compose.yaml restart
